name: normal-action

on:
    workflow_dispatch:
        inputs:
            flags:
                description: 'optional flags: -w, -n'
                required: false
                default: '-w'

jobs:
    setup-and-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Set up python
              uses: actions/setup-python@v2
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements_dev.txt
                  pip install .
            - name: Run API
              run: python -m github_actions_test.cli ${{ github.events.inputs.flags }}
            - name: save git status
              run: |
                  echo "GIT_STATUS<<EOF" >> $GITHUB_ENV
                  git status >> $GITHUB_ENV
                  echo "EOF" >> $GITHUB_ENV
            - name: save log content
              run: |
                  echo "LOG_CONTENT<<EOF" >> $GITHUB_ENV
                  cat log.log >> $GITHUB_ENV
                  echo "EOF" >> $GITHUB_ENV
            - name: check for warnings in log
              run: |
                  echo "WARNING_IN_LOG=${{ contains(env.LOG_CONTENT, 'WARNING') }}" >> $GITHUB_ENV
            - name: check for new files
              run: |
                  echo "NEW_FILES=${{ !contains(env.GIT_STATUS, 'nothing to commit') }}" >> $GITHUB_ENV
            - name: log all env variables
              run: |
                  echo "env.GIT_STATUS"
                  echo "$GIT_STATUS"
                  echo "env.NEW_FILES"
                  echo "$NEW_FILES"
                  echo "env.LOG_CONTENT"
                  echo "$LOG_CONTENT"
                  echo "env.WARNING_IN_LOG"
                  echo "$WARNING_IN_LOG"
            - name: push
              uses: github-actions-x/commit@v2.7
              with:
                  github-token: ${{ secrets.SECRET_TOKEN }}
                  push-branch: 'main'
                  commit-message: 'Update the reports'
                  force-add: 'true'
                  files: files/
                  name: github-actions
                  email: actions@github.com
