name: normal-action

on: workflow_dispatch

jobs:
    setup-and-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Set up python
              uses: actions/setup-python@v2
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements_dev.txt
                  pip install .
            - name: Run API
              # make the api log to a file
              run: github_actions_test
    commit-and-push:
        needs: setup-and-run
        runs-on: ubuntu-latest
        steps:
            - name: Commit changes
              run: |
                  git config --local user.email 'actions@github.com'
                  git config --local user.name 'github-actions'
                  git add files/
                  git commit -m 'Update the reports'
                  git push origin main


