name: normal-action

on: workflow_dispatch

jobs:
    setup-and-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Set up python
              uses: actions/setup-python@v2
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements_dev.txt
                  pip install .
            - name: Run API
              # make the api log to a file
              run: python github_actions_test/cli.py
            - name: list files
              run: |
                  pwd
                  ls -al
                  cd files
                  ls -al
                  cd ..
            - name: save git status
              run: |
                  echo "::set-env name=GIT_STATUS::$(git status)"
            - name: any new file
              env:
                NEW_FILES: ${{ !contains(env.GIT_STATUS, 'nothing to commit') }}
              run: |
                  echo "env.GIT_STATUS"
                  echo "$GIT_STATUS"
                  echo "env.NEW_FILES"
                  echo "$NEW_FILES"
            - name: push
              uses: github-actions-x/commit@v2.7
              with:
                  github-token: ${{ secrets.SECRET_TOKEN }}
                  push-branch: 'main'
                  commit-message: 'Update the reports'
                  force-add: 'true'
                  files: files/
                  name: github-actions
                  email: actions@github.com
